name             'tsuru'
maintainer       'Josh Blancett'
maintainer_email 'josh@firma8.com'
license          'All rights reserved'
description      'Installs/Configures tsuru'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.5.5'
depends           'apt'
depends           'docker'
depends           'aufs'
depends           'lxc'
